### ISSUE TITLE
本地背景音乐无法播放。

### ISSUE THREAD

**Issue by gikeihi** [FTTC/trtc-audio-mixer#1]
本地音乐的播放，是通过把选择的文件生成blob url 进行加载的，但是看源代码checkParams方法里有这么一句：

> var e = t.url.lastIndexOf("."),
> r = t.url.substr(e + 1);
> if (["mp3", "ogg", "wav", "flac"].indexOf(r) < 0)
>     throw new Error("文件类型不合理")
> 

因为是blob url这个check肯定是无法通过的啊。

**Comment by Goddywu** [comment]
同上

**Comment by dw1091751422** [comment]
同上

**Comment by dw1091751422** [comment]
> 同上

没人管啊 。不这么解决的

**Comment by zhangyuiris** [comment]
> 本地音乐的播放，是通过把选择的文件生成blob url 进行加载的，但是看源代码checkParams方法里有这么一句：
> 
> > var e = t.url.lastIndexOf("."),
> > r = t.url.substr(e + 1);
> > if (["mp3", "ogg", "wav", "flac"].indexOf(r) < 0)
> > throw new Error("文件类型不合理")
> 
> 因为是blob url这个check肯定是无法通过的啊。

0.0.9 版本已解决，请测试是否满足需求

**Comment by Goddywu** [comment]
我试了下更新为0.0.9，上传本地文件，还是报错： Uncaught Error: 文件类型不合理  @zhangyuiris

**Comment by xweiqingfei1** [comment]
我看了一下修改的部分，是判定了一下url是否以字符串blob开始。
如果这样判断就不能用README的示例来写了
README的示例是这样写的
`reader.readAsDataURL(file);`
这个并不会产生以blob开头的url。
除非这么写
`URL.createObjectURL(file); `

**Comment by gikeihi** [comment]
我看了一下修改的部分，是判定了一下url是否以字符串blob开始。
如果这样判断就不能用README的示例来写了
README的示例是这样写的
`reader.readAsDataURL(file);`
这个并不会产生以blob开头的url。
除非这么写
`URL.createObjectURL(file);`
